### ISSUE TITLE
DecryptMessage

### ISSUE THREAD

**Issue by JSanchezFDZ** [mrv777/ardorjs#24]
**Hello!**

I have used `encryptMessage` and everything works correctly.

The problem now comes when decrypting the message returned by Ardor.

I am trying to use `decryptNote` but it generates errors.

**NOTES**
- `isCompressed` should be true by default, since `encryptMessage` compresses it, right?

- `isText` should be set to true directly, there is nothing in the documentation.

- `byteArrayToString` uses deprecated functions.

`escape(String.fromCharCode.apply(null, bytes))` change it to `encodeURIComponent(String.fromCodePoint(...bytes))`

**ERROR** in _ardorjs/helpers -> byteArrayToString_
URIError: malformed URI sequence

**Comment by mrv777** [comment]
It's been a while since I worked with this.  I can try to take a look more later, but to start I believe it worked in Ardor Lite and you can take a look at it's use there: 

- https://github.com/mrv777/Ardor-Lite-Wallet/blob/master/src/pages/message-modal/message-modal.ts#L105
- https://github.com/mrv777/Ardor-Lite-Wallet/blob/master/src/providers/account-data/account-data.ts#L578

**Comment by JSanchezFDZ** [comment]
Thank you! I got the decryption to work but found a bug.

When the message is too small the decryption does not work.

It encrypts returning an array of 26 length (for example) but when decrypting it always returns minimum 32 length.

So it is not the same message and decryption fails.
I am still investigating this error, if I find a solution I will send you a pull request

![imagen](https://user-images.githubusercontent.com/17337482/220942112-0f864c9d-4046-4a4f-9cea-abf66f52fa27.png)
![imagen](https://user-images.githubusercontent.com/17337482/220941979-830222ab-2bd1-437b-a72b-10364ff1534e.png)

**Comment by MythicalBeings** [comment]
#25 **Bug is fixed in this pull request.**

**Comment by mrv777** [comment]
Thanks for figuring that out and making the PR
